"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TokenType = void 0;
var TokenType;
(function (TokenType) {
    TokenType["Identifier"] = "Identifier";
    TokenType["Number"] = "Number";
    TokenType["String"] = "String";
    TokenType["Barline"] = "Barline";
    TokenType["LBrak"] = "LBrak";
    TokenType["RBrak"] = "RBrak";
    TokenType["LParen"] = "LParen";
    TokenType["RParen"] = "RParen";
    TokenType["Dot"] = "Dot";
    TokenType["Hyphen"] = "Hyphen";
    TokenType["Underscore"] = "Underscore";
    TokenType["Asterisk"] = "Asterisk";
    TokenType["Caret"] = "Caret";
    TokenType["Slash"] = "Slash";
    TokenType["Accidental"] = "Accidental";
    TokenType["Colon"] = "Colon";
    TokenType["Semicolon"] = "Semicolon";
    TokenType["Equals"] = "Equals";
    TokenType["Newline"] = "Newline";
    TokenType["EOF"] = "EOF";
})(TokenType || (exports.TokenType = TokenType = {}));
